### ISSUE TITLE
Installing blendium

### ISSUE THREAD

**Issue by T4rt4rus** [Steveplays28/blendium#1]
I saw sb in the dh discord posting an image of using blendium with dh and a shader. But the issue is i am retarded and don't know how to insert that into dh or what to do. Help would be very much appreciated, thank you!

**Comment by Steveplays28** [comment]
Hi T4rt4rus, sorry for forgetting to respond earlier.
You can download Blendium via [GH Actions](https://gitthub.com/Steveplays28/blendium/actions) if you're signed in. Just click on `compiled_jar_files` and it should download a `zip` with the `jar` inside.

**Comment by T4rt4rus** [comment]
Thanks man!
