### ISSUE TITLE
Incompatible with DistantHorizons 2.0.1 (quilt)

### ISSUE THREAD

**Issue by NolanHewitt** [Steveplays28/blendium#12]
Using the newest version of distant horizons with blendium causes the Distant Horizons renderer to fail. 
https://cdn.discordapp.com/attachments/1181451186818252881/1181451190471491645/huge_2023-12-04_22.21.06.png?ex=65811b2a&is=656ea62a&hm=8485e8104efa58890f6a38250d967d7079fac4b80cb84bee8caeaa1ff72d496f&

**Comment by Steveplays28** [comment]
Hi NolanHewitt, thanks for the report.
I published a release with a fix for this issue (`v1.0.1`) just now, let me know how it goes.

**Comment by Aces-and-Jacks** [comment]
This fixed it for me
