### ISSUE TITLE
Unsure how to make blendium work with Iris shaders

### ISSUE THREAD

**Issue by starkgate** [Steveplays28/blendium#16]
I can see blending between DH LODs and vanilla Minecraft rendering, which looks quite nice. However, from the information given in the description, I cannot figure out a way to make blendium work with Iris shaders. Are there any extra steps / specific configuration options for it? Here is how it looks for me now (with BSL):

![image](https://github.com/Steveplays28/blendium/assets/12874678/02ef62c6-eeac-49c5-be9b-27ba834951a7)

**Comment by Steveplays28** [comment]
The blending feature from Blendium doesn't work with Iris shaderpacks. You'll need a [compatible shaderpack](https://gist.github.com/Steveplays28/52db568f297ded527da56dbe6deeec0e) for that.
Blendium has shaderpack settings presets for Iris, see the readme.

**Comment by starkgate** [comment]
> The blending feature from Blendium doesn't work with Iris shaderpacks. You'll need a [compatible shaderpack](https://gist.github.com/Steveplays28/52db568f297ded527da56dbe6deeec0e) for that. Blendium has shaderpack settings presets for Iris, see the readme.

Thank you, this document is what I was looking for. I believe it should be linked to in the description (in https://github.com/Steveplays28/blendium#optional).

**Comment by Steveplays28** [comment]
That is a good point, thanks for the suggestion. I'll link it when I have time!
