### ISSUE TITLE
crashes on launch

### ISSUE THREAD

**Issue by JohnWeak1** [Steveplays28/blendium#21]
whenever I am using this mod the game crashes on launch

mods used :
- blendium-1.0.1+mc1.20.x
- sodium-fabric-0.5.8+mc1.20.4
- indium-1.0.30+mc1.20.4
- DistantHorizons-fabric-2.0.2-a-dev-1.20.4
- iris-1.7.0-snapshot+mc1.20.4-dfec34d-dirty

game version :
fabric0.15.9+mc1.20.4

here are the logs : https://mclo.gs/IO5iNSv

**Comment by Steveplays28** [comment]
Duplicate of #19.
