### ISSUE TITLE
visual issues

### ISSUE THREAD

**Issue by TheNukeLore** [Steveplays28/blendium#3]
issue happens with just blendium and sodium. similar issue happens with the dh-comp compat pr for complimentary. no errors in log.

I have screenshots but as of the time of posting this issue, github is having issues with uploading images.

**Comment by GreenMan36** [comment]
![image](https://github.com/Steveplays28/blendium/assets/5887406/1a209c69-b882-40ee-8ede-1192f8ac69d6)

Not sure what the other user is talking about but I'll drop this here.
The clipping plane is quite obvious, would it be possible for it to be circular so its not so obvious when moving the camera and looking at the screen edges?

**Comment by Steveplays28** [comment]
Hi @GreenMan36, this is a different issue, feel free to drop by the Distant Horizons Discord.
The clipping plane is a straight line and can't be turned into a circle (easily) afaik.

**Comment by Steveplays28** [comment]
Closing as the leaf transparency issue has been worked around. Please open a new issue with more details if this is still a problem!
